name: Update streak stats

on:
  schedule:
    - cron: "*/5 * * * *" # Berjalan setiap jam
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Berjalan setiap kali file ini diubah
  workflow_dispatch: # Berjalan secara manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=radical&hide_border=true&fire=f472b6
          path: dist/streak-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "RusdiEneri"
          git config user.email "nuruddinrusydiilham@gmail.com"
          git add dist/streak-stats.svg
          git commit -m "Update streak stats" || exit 0
          git pull --rebase origin main
          git push
